# Site settings
title: Mercury
email: mercury@lists.mcs.anl.gov
description: > # this means to ignore newlines until "baseurl:"
  RPC for High-Performance Computing
baseurl: "/mercury" # the subpath of your site, e.g. /blog/
url: "http://www.mcs.anl.gov/projects" # the base hostname & protocol for your site
github_username:  mercury-hpc

# Build settings
markdown: kramdown
